language: node_js

node_js:
  - 'iojs'
  
branches:
    only:
        - master
  
install:
- npm install

script:
- jshint *.js

before_install: npm cache clean -f

notifications:
    email:
        jesse.kahner@gmail.com
